theme: jekyll-theme-merlot
title: API development guidelines for Raseel platform
description: This document illustrates most of the rules to follow by backend developers or integrators to write the APIs
